DROP DATABASE IF EXISTS personnel_db;
CREATE DATABASE personnel_db;

USE personnel_db;

CREATE TABLE departments (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
)

CREATE TABLE roles (
  id NOT NULL AUTO_INCREMENT PRIMARY KEY,
)

CREATE TABLE employees (
  id NOT NULL AUTO_INCREMENT PRIMARY KEY,
)